#!/sbin/openrc-run
# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

command=/usr/bin/moolticuted
command_args=""
pidfile=/var/run/moolticuted.pid

depend() {
	need local udev
}

start() {
	ebegin "Starting moolticuted"
	start-stop-daemon --start --background \
		--make-pidfile --pidfile $pidfile --exec $command -- $command_args
	eend $?
}
